### ISSUE TITLE
Download Data no longer downloads data, but rather new cohort ID and summary

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#208] opened 2023-12-31 21:04 UTC
![Screen Shot 2023-12-31 at 4 04 37 PM](https://github.com/MathematicalMedicine/diver-issues/assets/3909236/a45cf727-4463-4464-8f71-1b42d5d14c1e)
<img width="678" alt="Screen Shot 2023-12-31 at 4 04 45 PM" src="https://github.com/MathematicalMedicine/diver-issues/assets/3909236/d69ffd31-a7b4-4c34-b800-f0b3e51d30e4">

**Comment by WValenti** [comment] 2023-12-31 21:24
The table produced is wunderbar!
<img width="697" alt="Screen Shot 2023-12-31 at 4 24 15 PM" src="https://github.com/MathematicalMedicine/diver-issues/assets/3909236/6f1983c7-698e-4aca-983c-249f08d8eebf">

**Comment by Viqsi** [comment] 2024-01-02 17:45
Duplicate of #124

**Closed by Viqsi** 2024-01-02 17:45 UTC
