### ISSUE TITLE
the LIST* constraints as a new issue

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#31] opened 2022-03-10 15:38 UTC
Emailed Annalisa asking about the LIST* constraints and got this reply:

> LISTALL, LISTANY, and LISTNONE are intended to go with the proposed "list" variable which includes subvariables. The user selects the subvariables using checkboxes, and then is given a dropdown with "Any/All/None" that they then can apply a constraint to. 
> 
> You can set line 21 in  src/components/Constraints/ConstrainVariable.js to  variable.data_type = variable.data_type ? variable.data_type : VARIABLE_TYPES.LIST; and then select a variable as part of building a cohort to see the following:
> 
> <img width="640" alt="thumbnail_Screen Shot 2022-03-10 at 3 01 18 PM" src="https://user-images.githubusercontent.com/6570923/157690836-e321fba7-cd02-411b-b469-4441c3c6cd7c.png">
> 
> Right now all those subvariable options are hardcoded in src/components/Constraints/ChooseSubvariables.js.
> 
> You are right about those other constraint types you mentioned - the regex syntactic sugar ones. They simply correspond with the regex expressions defined src/utils/constants/constraints.js. You may have already found that, but I wanted to point it out in case you needed to refine those regex expressions.

It is at this point I must confess that I still don't know how that "List Variables" concept was actually supposed to work; I figured it was just a form of downcoding, but this is treating it as an explicit type, and I don't know which (if either) is correct.

_Originally posted by @Viqsi in https://github.com/mathmednet/diverweb-issues/issues/25#issuecomment-1064169397_

**Comment by WValenti** [comment] 2022-03-10 15:39
These cannot be implemented in the API or FE until the database supports them. This requires tagging qualified LIST variables as such, and returning (well, populating first) a table with the component information.

**Comment by Viqsi** [comment] 2022-09-05 23:09
I don't know if this was intended to be ready in time for the internal beta or not. I'm sure we'd be told it's high priority, but how does that priority compare to, um, everything *else* we need to be doing for internal beta?

Marking it as internal beta milestone for now so it at least doesn't get "lost". But maybe it'll shift. (Or maybe we'll reevaluate our timetable.)

**Comment by Viqsi** [comment] 2023-02-27 20:19
The code in this might serve as an alternate in-the-meantime workaround for #37. We've got some options. (I'm not sure how to adapt it to constructs, though, so it's not a panacea.)

**Comment by Viqsi** [comment] 2024-05-22 18:43
I'm killing this one off on my own initiative. It's not been brought up in years, and never evolved beyond "a special kind of downcoding", and that would be covered by multicategorical variables - which is another can of worms that we have yet to really address. Since that can of worms actually exists in some form in existing interview answers, however, I defer to keeping around the can that actually exists rather than the hypothetical one.

So it's getting the heave-ho along with a bunch of other old stuff I'm currently cleaning out.

**Closed** 2024-05-22 19:04 UTC
Labels: enhancement, not yet implemented, low priority
